# Graphics

## Outline {-}

##### 1. Introduction to ggplot2  {-}

- setup
- why ggplot2
- the evolution of a ggplot 
- create your first ggplot


##### 2. ggplot2 concepts   {-}

- the grammar of ggplot2
- geometrical layers
- statistical layers
- facets
- ggplots as objects

##### 3. Advanced customization   {-}

- scales
- coordinates
- labels
- annotations
- themes
- legends
- fonts

##### 4. Extensions  {-}
- patchwork
- gganimate
- ggplotly
- ggiraph




## Introduction

### setup  {-}
### intro to ggplot2   {-}
### why ggplot2   {-}
<!-- ### showcase (glimpse) {-} -->
### the evolution of a ggplot   {-}
<!-- ### showcase (in detail) {-} -->
### create your first ggplot  {-}


## ggplot2 concepts

### the grammar of ggplot2 {-}
<!-- ### walk through example {-} -->
### aesthetic mapping {-}
### geometrical layers {-}
#### geoms {-}
#### Setting vs Mapping of Visual Properties {-}
#### Local vs. Global Encoding {-}
#### Adding More Layers {-}
#### The `group` Aesthetic {-}
#### Overwrite Global Aesthetics {-}
### statistical layers {-}
####  `stat_*()` and `geom_*()` {-}
####  statistical summaries {-}
### facets {-}
### Store a ggplot as Object {-}
#### inspect a ggplot Object {-}
#### extend a ggplot Object {-}



## Advanced customization 

### scales {-}
#### continuous vs. discrete {-}
#### aesthetics + scales {-}
### coordinates {-}
### labels {-}
### annotations {-}
### themes {-}
### legends {-}
### fonts {-}


## Extensions

### ggplot2 extensions {-}
### gganimate {-}
### ggplotly {-}
### ggiraph {-}



